## Imports

In [6]:
import pandas as pd
import numpy as np
from tensorflow import keras
import tensorflow as tf

import matplotlib.pyplot as plt

import math
import warnings
warnings.simplefilter('ignore')

# Acquire

In [7]:
# Acquiring Gene Sequences with Class(Pos/Neg), the sequence itself, and ids
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/molecular-biology/promoter-gene-sequences/promoters.data'
names = ['Class', 'id', 'Sequence']
data = pd.read_csv(url, names = names)

In [8]:
data.shape

(106, 3)

In [9]:
data.head(10)

  Class         id                                           Sequence
0     +        S10  \t\ttactagcaatacgcttgcgttcggtggttaagtatgtataat...
1     +       AMPC  \t\ttgctatcctgacagttgtcacgctgattggtgtcgttacaat...
2     +       AROH  \t\tgtactagagaactagtgcattagcttatttttttgttatcat...
3     +      DEOP2  \taattgtgatgtgtatcgaagtgtgttgcggagtagatgttagaa...
4     +  LEU1_TRNA  \ttcgataattaactattgacgaaaagctgaaaaccactagaatgc...
5     +     MALEFG  \taggggcaaggaggatggaaagaggttgccgtataaagaaactag...
6     +       MALK  \t\tcagggggtggaggatttaagccatctcctgatgacgcatagt...
7     +       RECA  \t\ttttctacaaaacacttgatactgtatgagcatacagtataat...
8     +       RPOB  \t\tcgacttaatatactgcgacaggacgtccgttctgtgtaaatc...
9     +   RRNAB_P1  \tttttaaatttcctcttgtcaggccggaataactccctataatgc...

In [10]:
df = pd.DataFrame(data = pd.read_csv('SARS-Cov-II.csv'))

In [13]:
df.head(5)

,Nucleotide Accession,Species Taxonomy Id,Species Name,Virus Genus,Virus Family,Isolate Name,Nucleotide Length,Sequence Type,Nuc Completeness,Geo Location,US State,Host Name,Host Taxonomy ID,Collection Date,BioProject,BioSample
0,NC_045512.2,2697049,Severe acute respiratory syndrome coronavirus 2,Betacoronavirus,Coronaviridae,Wuhan-Hu-1,29903,RefSeq,complete,Asia; China,NaN,NaN,9606,2019-12,PRJNA485481,NaN
1,OK441679.1,2697049,Severe acute respiratory syndrome coronavirus 2,Betacoronavirus,Coronaviridae,SARS-CoV-2/human/USA/RI-CDCBI-RIDOH_XDEMEGSGS4...,29881,GenBank,complete,North America; USA: Rhode Island,NaN,NaN,9606,2021-09-27,PRJNA715749,SAMN22152966
2,OK440234.1,2697049,Severe acute respiratory syndrome coronavirus 2,Betacoronavirus,Coronaviridae,SARS-CoV-2/human/USA/MA-CDC-STM-000009972/2021,29825,GenBank,complete,North America; USA: Massachusetts,NaN,NaN,9606,2021-02-06,NaN,NaN
3,OK440225.1,2697049,Severe acute respiratory syndrome coronavirus 2,Betacoronavirus,Coronaviridae,SARS-CoV-2/human/USA/CA-CDC-STM-000008628/2021,29881,GenBank,complete,North America; USA: California,NaN,NaN,9606,2021-02-03,NaN,NaN
4,OK440221.1,2697049,Severe acute respiratory syndrome coronavirus 2,Betacoronavirus,Coronaviridae,SARS-CoV-2/human/USA/PA-CDC-STM-000005084/2021,29853,GenBank,complete,North America; USA: Pennsylvania,NaN,NaN,9606,2021-01-24,NaN,NaN